# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: 2e05db3fea9db1e0a8e3c84540219c7e0a0915ff # v0.4.3.9030
    hooks:
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        require_serial: true
      - id: lintr
      - id: readme-rmd-rendered
        exclude: reports/README.md
      - id: parsable-R
      - id: no-browser-statement
      - id: no-debug-statement
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=200']
      - id: mixed-line-ending
        args: ['--fix=no']
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
      - id: check-data-dict
        name: Data dictionary must be up to date with params file
        entry: Rscript R/hooks/check-data-dict.R
        files: (^|/)((params\.yaml)|(data-dict\.csv))$
        language: r
        additional_dependencies:
          - yaml
